/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackpadRouteImport } from './routes/trackpad'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiIpRouteImport } from './routes/api/ip'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as ApiWebrtcOfferRouteImport } from './routes/api/webrtc/offer'
import { Route as ApiWebrtcCandidatesRouteImport } from './routes/api/webrtc/candidates'
import { Route as ApiWebrtcAnswerRouteImport } from './routes/api/webrtc/answer'
import { Route as ApiTokenGenerateRouteImport } from './routes/api/token/generate'

const TrackpadRoute = TrackpadRouteImport.update({
  id: '/trackpad',
  path: '/trackpad',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIpRoute = ApiIpRouteImport.update({
  id: '/api/ip',
  path: '/api/ip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebrtcOfferRoute = ApiWebrtcOfferRouteImport.update({
  id: '/api/webrtc/offer',
  path: '/api/webrtc/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebrtcCandidatesRoute = ApiWebrtcCandidatesRouteImport.update({
  id: '/api/webrtc/candidates',
  path: '/api/webrtc/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebrtcAnswerRoute = ApiWebrtcAnswerRouteImport.update({
  id: '/api/webrtc/answer',
  path: '/api/webrtc/answer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokenGenerateRoute = ApiTokenGenerateRouteImport.update({
  id: '/api/token/generate',
  path: '/api/token/generate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/trackpad': typeof TrackpadRoute
  '/api/config': typeof ApiConfigRoute
  '/api/ip': typeof ApiIpRoute
  '/api/token/generate': typeof ApiTokenGenerateRoute
  '/api/webrtc/answer': typeof ApiWebrtcAnswerRoute
  '/api/webrtc/candidates': typeof ApiWebrtcCandidatesRoute
  '/api/webrtc/offer': typeof ApiWebrtcOfferRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/trackpad': typeof TrackpadRoute
  '/api/config': typeof ApiConfigRoute
  '/api/ip': typeof ApiIpRoute
  '/api/token/generate': typeof ApiTokenGenerateRoute
  '/api/webrtc/answer': typeof ApiWebrtcAnswerRoute
  '/api/webrtc/candidates': typeof ApiWebrtcCandidatesRoute
  '/api/webrtc/offer': typeof ApiWebrtcOfferRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/trackpad': typeof TrackpadRoute
  '/api/config': typeof ApiConfigRoute
  '/api/ip': typeof ApiIpRoute
  '/api/token/generate': typeof ApiTokenGenerateRoute
  '/api/webrtc/answer': typeof ApiWebrtcAnswerRoute
  '/api/webrtc/candidates': typeof ApiWebrtcCandidatesRoute
  '/api/webrtc/offer': typeof ApiWebrtcOfferRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/trackpad'
    | '/api/config'
    | '/api/ip'
    | '/api/token/generate'
    | '/api/webrtc/answer'
    | '/api/webrtc/candidates'
    | '/api/webrtc/offer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/trackpad'
    | '/api/config'
    | '/api/ip'
    | '/api/token/generate'
    | '/api/webrtc/answer'
    | '/api/webrtc/candidates'
    | '/api/webrtc/offer'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/trackpad'
    | '/api/config'
    | '/api/ip'
    | '/api/token/generate'
    | '/api/webrtc/answer'
    | '/api/webrtc/candidates'
    | '/api/webrtc/offer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  TrackpadRoute: typeof TrackpadRoute
  ApiConfigRoute: typeof ApiConfigRoute
  ApiIpRoute: typeof ApiIpRoute
  ApiTokenGenerateRoute: typeof ApiTokenGenerateRoute
  ApiWebrtcAnswerRoute: typeof ApiWebrtcAnswerRoute
  ApiWebrtcCandidatesRoute: typeof ApiWebrtcCandidatesRoute
  ApiWebrtcOfferRoute: typeof ApiWebrtcOfferRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trackpad': {
      id: '/trackpad'
      path: '/trackpad'
      fullPath: '/trackpad'
      preLoaderRoute: typeof TrackpadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ip': {
      id: '/api/ip'
      path: '/api/ip'
      fullPath: '/api/ip'
      preLoaderRoute: typeof ApiIpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webrtc/offer': {
      id: '/api/webrtc/offer'
      path: '/api/webrtc/offer'
      fullPath: '/api/webrtc/offer'
      preLoaderRoute: typeof ApiWebrtcOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webrtc/candidates': {
      id: '/api/webrtc/candidates'
      path: '/api/webrtc/candidates'
      fullPath: '/api/webrtc/candidates'
      preLoaderRoute: typeof ApiWebrtcCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webrtc/answer': {
      id: '/api/webrtc/answer'
      path: '/api/webrtc/answer'
      fullPath: '/api/webrtc/answer'
      preLoaderRoute: typeof ApiWebrtcAnswerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/token/generate': {
      id: '/api/token/generate'
      path: '/api/token/generate'
      fullPath: '/api/token/generate'
      preLoaderRoute: typeof ApiTokenGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  TrackpadRoute: TrackpadRoute,
  ApiConfigRoute: ApiConfigRoute,
  ApiIpRoute: ApiIpRoute,
  ApiTokenGenerateRoute: ApiTokenGenerateRoute,
  ApiWebrtcAnswerRoute: ApiWebrtcAnswerRoute,
  ApiWebrtcCandidatesRoute: ApiWebrtcCandidatesRoute,
  ApiWebrtcOfferRoute: ApiWebrtcOfferRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
